<script src="${pageContext.request.contextPath}/assets/js/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/popper.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/bootstrap.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/simplebar.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/daterangepicker.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/apps.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/moment.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/jquery.stickOnScroll.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/tinycolor-min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/config.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/d3.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/topojson.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/datamaps.all.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/datamaps-zoomto.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/datamaps.custom.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/Chart.min.js"></script>
<script>
    Chart.defaults.global.defaultFontFamily = base.defaultFontFamily;
    Chart.defaults.global.defaultFontColor = colors.mutedColor;
</script>
<script src="${pageContext.request.contextPath}/assets/js/gauge.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/jquery.sparkline.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/apexcharts.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/apexcharts.custom.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/jquery.mask.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/select2.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/jquery.steps.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/jquery.validate.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/jquery.timepicker.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/dropzone.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/uppy.min.js"></script>
<script src="${pageContext.request.contextPath}/assets/js/quill.min.js"></script>
